### ISSUE TITLE
Ads in a list view?

### ISSUE THREAD

**Issue by chernikovalexey** [larsacus/LARSAdController#119]
Hi,

That's more a question than an issue... Is it currently possible to insert ad banners between every 10 rows in a list view, e.g.? Is such a behaviour going to be banned or somehow restricted?

Alex.

**Comment by larsacus** [comment]
I think that is more of a question of "will  allow you to do this?" I don't see why you couldn't do it with a generic ad banner. That being said, this library doesn't support that kind of behavior currently since it internally manages the position of itself in a view controller. I don't have any support for manually positioning the ad banner location.
