### ISSUE TITLE
Having trouble hiding AdBanner when no ad is visible

### ISSUE THREAD

**Issue by robmontesinos** [larsacus/LARSAdController#121]
Hi there, thank you for your tremendous work with this controller.

I am having trouble hiding the banner and banner shadow when the ad is empty. I have several view controllers showing ads so I am using sub-classing to handle 'observeValueForKeyPath' and 'adController:(LARSAdController *)adController bannerChangedVisibility:(BOOL)anyBannerVisible'

The delegate method does not seem to be working reliably since I have several view controllers on the navigation controller stack, so I am relying on KVO in the super classes. A typical set up between super class and subclass looks as follows:

```ObjectiveC
- (void)adController:(LARSAdController *)adController bannerChangedVisibility:(BOOL)anyBannerVisible {
    NSLog(@"Changing visibility: %@ on %@", anyBannerVisible ? @"visible" : @"hidden", NSStringFromClass([self class]));
    if (anyBannerVisible && [self shouldDisplayAds] && !self.ignoreAds)
        [self showAdBanner];
    else
        [self hideAdBanner];        
}

- (void)observeValueForKeyPath:(NSString *)keyPath ofObject:(id)object change:(NSDictionary *)change context:(void *)context {
    if ([keyPath isEqualToString:kLARSAdObserverKeyPathIsAdVisible]) {
        NSLog(@"Observing keypath \"%@\" on %@", keyPath, NSStringFromClass([self class]));

        BOOL anyAdsVisible = [change[NSKeyValueChangeNewKey] boolValue];
        
        // get a reference to the banner that is currently visible
        UIView *bannerView = nil;
        NSArray *instances = [[[LARSAdController sharedManager] adapterInstances] allValues];
        for (id <TOLAdAdapter> adapterInstance in instances) {
            bannerView = adapterInstance.bannerView;
        }
        
        if (!self.ignoreAds) {
            if (anyAdsVisible && [self shouldDisplayAds]) {
                NSLog(@"--->AD IS VISIBLE!!");
                [self showAdBanner];
            } else {
                NSLog(@"--->AD IS NOT VISIBLE!!");
                [self hideAdBanner];
            }
        }
    }
}

- (void)hideAdBanner {
    NSLog(@">>> Entering %s <<<", __PRETTY_FUNCTION__);
    [LARSAdController sharedManager].containerView.hidden = ![LARSAdController sharedManager].isAdVisible;
}

- (void)showAdBanner {
    NSLog(@">>> Entering %s <<<", __PRETTY_FUNCTION__);
    [LARSAdController sharedManager].containerView.hidden = ![LARSAdController sharedManager].isAdVisible;
}

subclasses control the tableView layout constraints like so:

```ObjectiveC
- (void)showAdBanner {
    [super showAdBanner];
    NSLog(@">>> Entering %s <<<", __PRETTY_FUNCTION__);
    [self animateTableViewBottomConstraint:kBannerHeight];
}

- (void)hideAdBanner {
    [super hideAdBanner];
    NSLog(@">>> Entering %s <<<", __PRETTY_FUNCTION__);
    [self animateTableViewBottomConstraint:0.0];
}

- (void)animateTableViewBottomConstraint:(CGFloat)newConstant {
    NSLog(@">>> Entering %s <<<", __PRETTY_FUNCTION__);
    [self.view layoutIfNeeded];
    
    __weak typeof(self)weakSelf = self;
    [UIView animateWithDuration:0.25
                     animations:^{
                         weakSelf.tableViewBottomConstraint.constant = newConstant;
                         [weakSelf.view layoutIfNeeded];
                     }
     ];
}

Would you mind suggesting a way that I could control the adBanner appearance more reliably? Thank you in advance.

**Comment by larsacus** [comment]
I think I may be a little confused still as to what you're trying to accomplish. So you're trying to manually force-hide the ads in a custom way when it reports that it does not have an ad visible?

I'm also unclear as to what you mean by "I have several view controllers showing ads so I am using sub-classing". Does this mean that you have several view controllers visible on screen at once that are all trying to display the same banner ad? You should really only be displaying a single ad banner on screen at a time. In fact, this component is only using a single instance under the hood, so you will only ever have one instance to work with. If you are saying you're just pushing a bunch of VCs on a stack, then you should just be able to add the ad controller to each view controller as they are pushed/popped off of the stack (like in viewWillAppear).

I _am_ curious to know why the delegation doesn't seem to be working for you. This is the first report I've gotten of it not working.

The original intention of this library was to make it a simple 1- to 2-line drop-in to get ads displaying in your app for the 80% use-case. The delegate pattern was added to replace KVO since it is so much easier to use for the cases where you need to adjust your UI to accommodate for the presence of an ad. As for what it looks like you're trying to do here, you might be better off using the iAd APIs directly and integrating the ads directly since it looks like you want to do some more custom things that might be out of the 80% use-case of this component. That being said, based on the code you have posted above, you _should_ be able to simple rely on the delegate pattern to adjust your UI (what looks like adjusting a table view's bottom constant up/down) depending on the presence of an ad. You shouldn't have to do any more with the ad container at all.

**Comment by robmontesinos** [comment]
Thank you Lars for your quick reply. My apologies for not being very clear.

In terms of sub-classing, I have a basic VC that I sub-class that contains redundant calls such as show alert, check network connections, Facebook and Twitter shares, etc. It is here that I placed the delegate and KVO methods. I am displaying only one banner per screen.

The delegate is a great addition and it is now working - I had become confused between KVO and delegate and they were not being set properly (by me).

I believe it is working now with just a few tweaks - setting the delegate on each VC's viewDidAppear method in the parent class and removing the KVO. 

Quick question: if I call destroyAllAdBanners off an InApp Purchase transaction, all I have to do is restore my layout constraints and the banner will not return?

Thank you for helping me out again Lars!!

**Comment by larsacus** [comment]
I'm glad you got it working!

And yes, `destroyAllAdBanners` was designed specifically for the use-case of a user purchasing/doing something to remove ads. This should do all of the necessary cleanup to tear down all of the ads and not make any more requests. All you have to do is reposition your UI to account for not having ads anymore and prevent any further calls to the ad controller to prevent making requests again :smirk:

**Comment by robmontesinos** [comment]
Thank you @larsacus - your advice really did light the way to solve this problem for me. And the destroyAllAdBanners will come in very handy. Hope all is going well with you. SAlud!

**Comment by larsacus** [comment]
Best of luck! :beers:

**Comment by robmontesinos** [comment]
Hi @larsacus - one more question please: I got the control of ad banner visible/not visible working well. The only thing is I can't figure what to do with the shadow which is present when the ad banner is hidden. How can I hide/un-hide the shadow also? Thank you man

**Comment by larsacus** [comment]
Ah, yes. It looks like that shadow is not currently being conditionally removed when the ad banner is in the hidden state.

**Comment by robmontesinos** [comment]
Ok thank you. I looked around for a way to turn it off but didn't feel comfortable messing with it. Salud!

**Comment by robmontesinos** [comment]
@larsacus Hi Lars, is there going to be anything going on with the shadow?

**Comment by larsacus** [comment]
I haven't dedicated any time specifically to removing the shadow.

I welcome any pull requests if you'd like to take a shot at something to be generically useful.

**Comment by robmontesinos** [comment]
@larsacus I hear you. I'll do some research on how to do a Pull Request and keep you posted. Thank you
